[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.build]
cmds = ["npm install --include=dev", "npm run build", "npx prisma generate"]

[start]
cmd = "npx prisma db push --skip-generate && node server/index.js"
